name: derm_pix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  qr_flutter: ^4.1.0


  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  firebase_database: ^10.5.7
  firebase_storage: ^11.6.9
  mobile_scanner: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
